FROM hexpm/elixir:1.16.0-erlang-26.2.1-debian-bullseye-20231009 as test

RUN apt-get update && \
    apt-get install -y git build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV MIX_ENV=test

WORKDIR /app

RUN mix local.hex --force && \
    mix local.rebar --force

COPY mix.exs mix.lock ./
COPY config config

RUN mix deps.get

COPY test test

COPY lib lib
COPY priv priv

RUN mix compile

CMD ["mix", "test"]